---
tags: [spring-boot, groovy, test]
projects: [spring-boot]
---
:spring_boot_version: 1.5.6.RELEASE
:spring-boot: https://github.com/spring-projects/spring-boot
:toc:
:icons: font
:source-highlighter: prettify
:project_id: gs-spring-boot
本指南提供了一个示例，演示了 {spring-boot}[Spring Boot] 如何帮助你加速和促进应用开发。当您阅读更多的Spring入门指南时，您会看到更多的Spring Boot用例。它的目的是让你快速尝试Spring Boot。如果你想创建自己的Spring Boot为基础的项目，访问http://start.knos.top/[Spring Initializr]，方括号中填写您的项目的详细信息，选择你的选项，你可以下载Maven构建文件，或将项目打包为一个zip文件。

== 你将构建什么
您将使用Spring Boot构建一个简单的Web应用程序，并向它添加一些有用的服务。

== 你需要什么

:java_version: 1.8
include::https://raw.githubusercontent.com/webGoBetter/getting-started-macros/master/prereq_editor_jdk_buildtools.adoc[]

include::https://raw.githubusercontent.com/webGoBetter/getting-started-macros/master/how_to_complete_this_guide.adoc[]


include::https://raw.githubusercontent.com/webGoBetter/getting-started-macros/master/hide-show-gradle.adoc[]

include::https://raw.githubusercontent.com/webGoBetter/getting-started-macros/master/hide-show-maven.adoc[]

include::https://raw.githubusercontent.com/webGoBetter/getting-started-macros/master/hide-show-sts.adoc[]

== 了解用Spring Boot你可以做什么

Spring Boot提供了一种快速构建应用程序的方法。在你的classpath和你已经配置了Beans中寻找，对你省略的设置做出合理的假设，然后添加进去。使用Spring Boot，您可以更多地关注业务特性，而较少关注基础设施。

举个例子:

- 有Spring MVC吗？有几个特定的bean，你几乎总是需要，所以Spring Boot自动添加它们。Spring MVC应用程序还需要一个servlet容器，因此Spring Boot会自动配置一个嵌入式Tomcat。
- 有Jetty吗？如果是这样，你可能不希望Tomcat，而是嵌入Jetty。Spring Boot为您处理。
- 有Thymeleaf吗？有几个bean必须始终添加到应用程序上下文中；Spring Boot会将它们添加到您的应用程序中。

这些只是Spring Boot提供的自动配置的几个例子。同时，Spring Boot不会妨碍你的工作。例如，如果Thymeleaf在你的类路径上，Spring Boot会自动添加一个  `SpringTemplateEngine` 到你的应用程序的上下文中。但是如果你在你自己的设置里定义了你自己的 `SpringTemplateEngine` ，那么Spring Boot就不会添加它了。只需要一点点工作就可以让你控制这一切。

NOTE: Spring Boot 不生成代码或对文件进行编辑。相反，当启动应用程序时，Spring Boot 动态地将bean和设置连接起来，并将它们应用到应用程序上下文中。

== 创建一个简单的Web应用程序
现在您可以为一个简单的Web应用程序创建一个Web控制器。

`src/main/java/hello/HelloController.java`
[source,java]
----
include::initial/src/main/java/hello/HelloController.java[]
----

这个类被标记为一个 `@RestController` ，意思是准备使用Spring MVC处理Web请求。 `@RequestMapping` 映射 `/` 到 `index()` 方法。当从浏览器调用或使用命令行上的 curl 时，该方法返回纯文本。这是因为 `@RestController` 结合 `@Controller` 和 `@ResponseBody` ，这两个注释会是在Web请求返回的结果是数据而不是一个视图。

== 创建应用程序类
在这里，您用组件创建一个应用程序类:

`src/main/java/hello/Application.java`
[source,java]
----
include::complete/src/main/java/hello/Application.java[]
----

include::https://raw.githubusercontent.com/webGoBetter/getting-started-macros/master/spring-boot-application.adoc[]

还有一个 `CommandLineRunner` 方法标记为 `@Bean` ，这会在应用启动时运行。它检索你的应用程序创建的所有bean，或者Spring Boot自动添加的。它会将它们排序后打印出来。

== 运行应用程序
运行应用程序，执行:

[subs="attributes"]
----
./gradlew build && java -jar build/libs/{project_id}-0.1.0.jar
----

如果你使用 Maven, 执行:

[subs="attributes"]
----
mvn package && java -jar target/{project_id}-0.1.0.jar
----

你应该看到一些这样的输出:

....
Let's inspect the beans provided by Spring Boot:
application
beanNameHandlerMapping
defaultServletHandlerMapping
dispatcherServlet
embeddedServletContainerCustomizerBeanPostProcessor
handlerExceptionResolver
helloController
httpRequestHandlerAdapter
messageSource
mvcContentNegotiationManager
mvcConversionService
mvcValidator
org.springframework.boot.autoconfigure.MessageSourceAutoConfiguration
org.springframework.boot.autoconfigure.PropertyPlaceholderAutoConfiguration
org.springframework.boot.autoconfigure.web.EmbeddedServletContainerAutoConfiguration
org.springframework.boot.autoconfigure.web.EmbeddedServletContainerAutoConfiguration$DispatcherServletConfiguration
org.springframework.boot.autoconfigure.web.EmbeddedServletContainerAutoConfiguration$EmbeddedTomcat
org.springframework.boot.autoconfigure.web.ServerPropertiesAutoConfiguration
org.springframework.boot.context.embedded.properties.ServerProperties
org.springframework.context.annotation.ConfigurationClassPostProcessor.enhancedConfigurationProcessor
org.springframework.context.annotation.ConfigurationClassPostProcessor.importAwareProcessor
org.springframework.context.annotation.internalAutowiredAnnotationProcessor
org.springframework.context.annotation.internalCommonAnnotationProcessor
org.springframework.context.annotation.internalConfigurationAnnotationProcessor
org.springframework.context.annotation.internalRequiredAnnotationProcessor
org.springframework.web.servlet.config.annotation.DelegatingWebMvcConfiguration
propertySourcesBinder
propertySourcesPlaceholderConfigurer
requestMappingHandlerAdapter
requestMappingHandlerMapping
resourceHandlerMapping
simpleControllerHandlerAdapter
tomcatEmbeddedServletContainerFactory
viewControllerHandlerMapping
....

你可以清楚地看到 **org.springframework.boot.autoconfigure** 的bean. 还有一个 `tomcatEmbeddedServletContainerFactory`.

查看服务.

....
$ curl localhost:8080
Greetings from Spring Boot!
....

== 添加单元测试

您需要为您添加的端点添加一个测试，Spring测试已经提供了一些机制，并且很容易包含在您的项目中。

将此添加到构建文件的依赖列表中：

[source,groovy]
----
include::complete/build.gradle[tag=tests]
----

如果你使用Maven, 把这个添加到你的依赖列表中:

[source,xml]
----
include::complete/pom.xml[tag=tests]
----

现在写一个简单的单元测试，mock 通过你的终点的servlet请求和响应：

`src/test/java/hello/HelloControllerTest.java`
[source,java]
----
include::complete/src/test/java/hello/HelloControllerTest.java[]
----

The `MockMvc` comes from Spring Test and allows you, via a set of convenient builder classes, to send HTTP requests into the `DispatcherServlet` and make assertions about the result. Note the use of the `@AutoConfigureMockMvc` together with `@SpringBootTest` to inject a `MockMvc` instance. Having used `@SpringBootTest` we are asking for the whole application context to be created.  An alternative would be to ask Spring Boot to create only the web layers of the context using the `@WebMvcTest`. Spring Boot automatically tries to locate the main application class of your application in either case, but you can override it, or narrow it down, if you want to build something different.

As well as mocking the HTTP request cycle we can also use Spring Boot to write a very simple full-stack integration test. For example, instead of (or as well as) the mock test above we could do this:

`src/test/java/hello/HelloControllerIT.java`
[source,java]
----
include::complete/src/test/java/hello/HelloControllerIT.java[]
----

The embedded server is started up on a random port by virtue of the `webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT` and the actual port is discovered at runtime with the `@LocalServerPort`.

== Add production-grade services
If you are building a web site for your business, you probably need to add some management services. Spring Boot provides several out of the box with its http://docs.spring.io/spring-boot/docs/{spring_boot_version}/reference/htmlsingle/#production-ready[actuator module], such as health, audits, beans, and more.

Add this to your build file's list of dependencies:

[source,groovy]
----
include::complete/build.gradle[tag=actuator]
----

If you are using Maven, add this to your list of dependencies:

[source,xml]
----
include::complete/pom.xml[tag=actuator]
----

Then restart the app:

[subs="attributes"]
----
./gradlew build && java -jar build/libs/{project_id}-0.1.0.jar
----

If you are using Maven, execute:

[subs="attributes"]
----
mvn package && java -jar target/{project_id}-0.1.0.jar
----

You will see a new set of RESTful end points added to the application. These are management services provided by Spring Boot.

....
2014-06-03 13:23:28.119  ... : Mapped "{[/error],methods=[],params=[],headers=[],consumes...
2014-06-03 13:23:28.119  ... : Mapped "{[/error],methods=[],params=[],headers=[],consumes...
2014-06-03 13:23:28.136  ... : Mapped URL path [/**] onto handler of type [class org.spri...
2014-06-03 13:23:28.136  ... : Mapped URL path [/webjars/**] onto handler of type [class ...
2014-06-03 13:23:28.440  ... : Mapped "{[/info],methods=[GET],params=[],headers=[],consum...
2014-06-03 13:23:28.441  ... : Mapped "{[/autoconfig],methods=[GET],params=[],headers=[],...
2014-06-03 13:23:28.441  ... : Mapped "{[/mappings],methods=[GET],params=[],headers=[],co...
2014-06-03 13:23:28.442  ... : Mapped "{[/trace],methods=[GET],params=[],headers=[],consu...
2014-06-03 13:23:28.442  ... : Mapped "{[/env/{name:.*}],methods=[GET],params=[],headers=...
2014-06-03 13:23:28.442  ... : Mapped "{[/env],methods=[GET],params=[],headers=[],consume...
2014-06-03 13:23:28.443  ... : Mapped "{[/configprops],methods=[GET],params=[],headers=[]...
2014-06-03 13:23:28.443  ... : Mapped "{[/metrics/{name:.*}],methods=[GET],params=[],head...
2014-06-03 13:23:28.443  ... : Mapped "{[/metrics],methods=[GET],params=[],headers=[],con...
2014-06-03 13:23:28.444  ... : Mapped "{[/health],methods=[GET],params=[],headers=[],cons...
2014-06-03 13:23:28.444  ... : Mapped "{[/dump],methods=[GET],params=[],headers=[],consum...
2014-06-03 13:23:28.445  ... : Mapped "{[/beans],methods=[GET],params=[],headers=[],consu...
....

They include: errors, http://localhost:8080/env[environment], http://localhost:8080/health[health], http://localhost:8080/beans[beans], http://localhost:8080/info[info], http://localhost:8080/metrics[metrics], http://localhost:8080/trace[trace], http://localhost:8080/configprops[configprops], and http://localhost:8080/dump[dump].

NOTE: There is also a `/shutdown` endpoint, but it's only visible by default via JMX. To http://docs.spring.io/spring-boot/docs/{spring_boot_version}/reference/htmlsingle/#production-ready-customizing-endpoints[enable it as an HTTP endpoint], add
`endpoints.shutdown.enabled=true` to your `application.properties` file.

It's easy to check the health of the app.

----
$ curl localhost:8080/health
{"status":"UP","diskSpace":{"status":"UP","total":397635555328,"free":328389529600,"threshold":10485760}}}
----

You can try to invoke shutdown through curl.

----
$ curl -X POST localhost:8080/shutdown
{"timestamp":1401820343710,"error":"Method Not Allowed","status":405,"message":"Request method 'POST' not supported"}
----

Because we didn't enable it, the request is blocked by the virtue of not existing.

For more details about each of these REST points and how you can tune their settings with an `application.properties` file, you can read detailed http://docs.spring.io/spring-boot/docs/{spring_boot_version}/reference/htmlsingle/#production-ready-endpoints[docs about the endpoints].

== 查看Spring Boot starter程序
You have seen some of http://docs.spring.io/spring-boot/docs/{spring_boot_version}/reference/htmlsingle/#using-boot-starter[Spring Boot's "starters"]. You can see them all https://github.com/spring-projects/spring-boot/tree/master/spring-boot-starters[here in source code].

== jar支持和Groovy支持
The last example showed how Spring Boot makes it easy to wire beans you may not be aware that you need. And it showed how to turn on convenient management services.

But Spring Boot does yet more. It supports not only traditional WAR file deployments, but also makes it easy to put together executable JARs thanks to Spring Boot's loader module. The various guides demonstrate this dual support through the `spring-boot-gradle-plugin` and `spring-boot-maven-plugin`.

On top of that, Spring Boot also has Groovy support, allowing you to build Spring MVC web apps with as little as a single file.

Create a new file called **app.groovy** and put the following code in it:

[source,groovy]
----
@RestController
class ThisWillActuallyRun {

    @RequestMapping("/")
    String home() {
        return "Hello World!"
    }

}
----

NOTE: It doesn't matter where the file is. You can even fit an application that small inside a https://twitter.com/rob_winch/status/364871658483351552[single tweet]!

Next, http://docs.spring.io/spring-boot/docs/{spring_boot_version}/reference/htmlsingle/#getting-started-installing-the-cli[install Spring Boot's CLI].

Run it as follows:

----
$ spring run app.groovy
----

NOTE: This assumes you shut down the previous application, to avoid a port collision.

From a different terminal window:
----
$ curl localhost:8080
Hello World!
----

Spring Boot does this by dynamically adding key annotations to your code and using http://groovy.codehaus.org/Grape[Groovy Grape] to pull down libraries needed to make the app run.

== 总结
Congratulations! You built a simple web application with Spring Boot and learned how it can ramp up your development pace. You also turned on some handy production services.
This is only a small sampling of what Spring Boot can do. Checkout http://docs.spring.io/spring-boot/docs/{spring_boot_version}/reference/htmlsingle[Spring Boot's online docs]
if you want to dig deeper.

== 参见

The following guides may also be helpful:

* https://spring.io/guides/gs/securing-web/[Securing a Web Application]
* https://spring.io/guides/gs/serving-web-content/[Serving Web Content with Spring MVC]

include::https://raw.githubusercontent.com/webGoBetter/getting-started-macros/master/footer.adoc[]
